services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means

  Aropixel\PageBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../AropixelPageBundle.php'
      - '../../Resources/'

  aropixel.page.form.factory:
    class: Aropixel\PageBundle\Form\FormFactory
    arguments: ['@form.factory']
    public: true

  Aropixel\PageBundle\EventListener\MappedSuperClassListener:
    arguments: ['%aropixel_page.entities%', '@parameter_bag']
    tags:
      - { name: doctrine.event_listener, event: 'loadClassMetadata', priority: 8192 }

  Aropixel\PageBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]

  Aropixel\PageBundle\Component\Builder\SectionColors:
    arguments:
      $colors: '%aropixel_page.page_builder.section_colors%'

  Aropixel\PageBundle\Component\Builder\UiKitPageBuilderRenderer:
    arguments:
      $customBlockRenderers: !tagged_iterator aropixel_page.block_renderer

  Aropixel\PageBundle\Component\Builder\BootstrapPageBuilderRenderer:
    arguments:
      $customBlockRenderers: !tagged_iterator aropixel_page.block_renderer

  Aropixel\PageBundle\Component\Security\PageAccessCheckerInterface:
    alias: Aropixel\PageBundle\Component\Security\AllowAllPageAccessChecker

  Aropixel\PageBundle\Component\Builder\BlockPolicy:
    arguments:
      $allowedBlocks: '%aropixel_page.page_builder.allowed_blocks%'
      $requiredBlocks: '%aropixel_page.page_builder.required_blocks%'

  Aropixel\PageBundle\Component\Builder\RoutePageUrlGenerator:
    arguments:
      $routeName: '%aropixel_page.page_builder.front_route.name%'
      $routeParameter: '%aropixel_page.page_builder.front_route.parameter%'
      $includeParent: '%aropixel_page.page_builder.front_route.include_parent%'

  Aropixel\PageBundle\Component\Builder\PageUrlGeneratorInterface:
    alias: Aropixel\PageBundle\Component\Builder\RoutePageUrlGenerator

  Aropixel\PageBundle\Controller\Builder\BuilderAction:
    arguments:
      $pageBuilderConfig: '%aropixel_page.page_builder%'

  Aropixel\PageBundle\Controller\Builder\PreviewAction:
    arguments:
      $pageBuilderConfig: '%aropixel_page.page_builder%'

  aropixel.page.form.default:
    class: '%aropixel_page.form.default%'
    tags: ['aropixel.page.form']

  aropixel.page.form.default_translatable:
    class: '%aropixel_page.form.default_translatable%'
    tags: [ 'aropixel.page.form' ]

  Aropixel\PageBundle\Repository\:
    resource: '../../Repository'
    autowire: true
    tags: ['doctrine.repository_service']
